import { IUser } from "./types";

export const users: IUser[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    username: "johndoe",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    username: "janesmith",
  },
  {
    id: 3,
    firstName: "Alice",
    email: "alice@example.com",
    username: "alice123",
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@example.com",
    username: "bob.j",
  },
  {
    id: 5,
    firstName: "Eva",
    lastName: "Anderson",
    email: "eva.anderson@example.com",
    username: "eva_a",
  },
  {
    id: 6,
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie.brown@example.com",
    username: "charlie_b",
  },
  {
    id: 7,
    firstName: "Grace",
    email: "grace@example.com",
    username: "grace89",
  },
  {
    id: 8,
    firstName: "Daniel",
    lastName: "Miller",
    email: "daniel.miller@example.com",
    username: "dmiller",
  },
  {
    id: 9,
    firstName: "Sophia",
    lastName: "Davis",
    email: "sophia.davis@example.com",
    username: "sophiad",
  },
  {
    id: 10,
    firstName: "Liam",
    email: "liam@example.com",
    username: "liam_123",
  },
  {
    id: 11,
    firstName: "Olivia",
    lastName: "Taylor",
    email: "olivia.taylor@example.com",
    username: "olivia_t",
  },
  {
    id: 12,
    firstName: "Mason",
    lastName: "White",
    email: "mason.white@example.com",
    username: "masonw",
  },
  { id: 13, firstName: "Ava", email: "ava@example.com", username: "ava34" },
  {
    id: 14,
    firstName: "Noah",
    lastName: "Smith",
    email: "noah.smith@example.com",
    username: "noahs",
  },
  {
    id: 15,
    firstName: "Emma",
    lastName: "Brown",
    email: "emma.brown@example.com",
    username: "emmab",
  },
  {
    id: 16,
    firstName: "Logan",
    email: "logan@example.com",
    username: "logan87",
  },
  {
    id: 17,
    firstName: "Isabella",
    lastName: "Johnson",
    email: "isabella.j@example.com",
    username: "isabellaj",
  },
  {
    id: 18,
    firstName: "Ethan",
    email: "ethan@example.com",
    username: "ethan123",
  },
  {
    id: 19,
    firstName: "Mia",
    lastName: "Jones",
    email: "mia.jones@example.com",
    username: "miaj",
  },
  {
    id: 20,
    firstName: "Carter",
    lastName: "Miller",
    email: "carter.miller@example.com",
    username: "carterm",
  },
  {
    id: 21,
    firstName: "Elijah",
    lastName: "Williams",
    email: "elijah.w@example.com",
    username: "elijahw",
  },
  {
    id: 22,
    firstName: "Avery",
    lastName: "Moore",
    email: "avery.moore@example.com",
    username: "averym",
  },
  {
    id: 23,
    firstName: "Abigail",
    lastName: "Wilson",
    email: "abigail.w@example.com",
    username: "abigailw",
  },
  {
    id: 24,
    firstName: "Jackson",
    lastName: "Jones",
    email: "jackson.j@example.com",
    username: "jacksonj",
  },
  {
    id: 25,
    firstName: "Scarlett",
    lastName: "Davis",
    email: "scarlett.d@example.com",
    username: "scarlettd",
  },
  {
    id: 26,
    firstName: "Lucas",
    lastName: "Harris",
    email: "lucas.h@example.com",
    username: "lucash",
  },
  {
    id: 27,
    firstName: "Aria",
    lastName: "Thompson",
    email: "aria.t@example.com",
    username: "ariat",
  },
  {
    id: 28,
    firstName: "Grayson",
    lastName: "Martin",
    email: "grayson.m@example.com",
    username: "graysonm",
  },
  {
    id: 29,
    firstName: "Hazel",
    lastName: "Mitchell",
    email: "hazel.m@example.com",
    username: "hazelm",
  },
  {
    id: 30,
    firstName: "Liam",
    lastName: "Reed",
    email: "liam.r@example.com",
    username: "liamr",
  },
  {
    id: 31,
    firstName: "Penelope",
    lastName: "Baker",
    email: "penelope.b@example.com",
    username: "penelopeb",
  },
  {
    id: 32,
    firstName: "Mason",
    lastName: "Fisher",
    email: "mason.f@example.com",
    username: "masonf",
  },
  {
    id: 33,
    firstName: "Eleanor",
    lastName: "Perez",
    email: "eleanor.p@example.com",
    username: "eleanorp",
  },
  {
    id: 34,
    firstName: "Caleb",
    lastName: "Ramirez",
    email: "caleb.r@example.com",
    username: "calebr",
  },
  {
    id: 35,
    firstName: "Madison",
    lastName: "Ward",
    email: "madison.w@example.com",
    username: "madisonw",
  },
  {
    id: 36,
    firstName: "Ezra",
    lastName: "Lopez",
    email: "ezra.l@example.com",
    username: "ezral",
  },
  {
    id: 37,
    firstName: "Chloe",
    lastName: "Barnes",
    email: "chloe.b@example.com",
    username: "chloeb",
  },
  {
    id: 38,
    firstName: "Henry",
    lastName: "Russell",
    email: "henry.r@example.com",
    username: "henryr",
  },
  {
    id: 39,
    firstName: "Violet",
    lastName: "Simmons",
    email: "violet.s@example.com",
    username: "violets",
  },
  {
    id: 40,
    firstName: "Leo",
    lastName: "Turner",
    email: "leo.t@example.com",
    username: "leot",
  },
];
